### ISSUE TITLE
Multi-gestures and wake don't work

### ISSUE THREAD

**Issue by chr0sy** [SkyrilHD/Dell-Exx50-Hackintosh#3] opened 2021-01-04 19:59 UTC
Hi. I tried your EFI and everything works except for multi-gestures (they worked on the first boot weirdly, and then when I rebooted they don't work anymore. the 3 finger swipe corresponds to another function all together not the mission control or changing pages), other gestures don't work as well just the scroll. 

also the wake from sleep doesn't work for me. it didn't with any of the efi's i've tried so far, you have any idea what could be the issue? it's really bugging me 🙁. it goes to sleep perfectly fine, then it takes ±4 minutes to wake, it's like the display takes a lot to come back to life.

**Comment by SkyrilHD** [comment] 2021-01-04 20:30
About the problem with multitouch gestures: Since the VoodooPS2 kext is 2-3 years old since it was updated, there are basically no multitouch gestures other than 3-finger swiping. I've published my settings in my other repo, which you can find [here](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/issues/8#issuecomment-669966730). These settings are confirmed to work. We use an old kext because it is the "only one" that works with our model. For example, Acidanthera's VoodooPS2 kext doesn't even recognize the trackpad.

The wake bug does not occur with my E7250. So maybe mention your model. Can you try pressing a key on the keyboard when you open the lid?

**Comment by chr0sy** [comment] 2021-01-04 20:37
Ah, weird thing was when I first copied your EFI every gesture worked! It was weird but I could swipe through pages, full screen apps, 3 finger swipe for mission control worked! Now none of these work, instead when I do 3 finger swipe, some folders on desktop get selected or menu items on the top bar.

About wake, I have a E7450. Same specs as you except 8GB ram. Whatever I do, it just simply takes 4 minutes to wake. When it wakes, all electron apps like Google Chrome do not work anymore. I basically can't use sleep wake at all :( any idea how to fix it? Something different from you is that I am using AirportIltwm for wireless intel.

**Comment by SkyrilHD** [comment] 2021-01-04 20:46
OK. This wake bug is a weird one. Could you run `pmset -g log > pmset_log.txt` in Terminal and send the file to me? I also use AirportItlwm and never had any problems. I use the debug 1.2.0 version though.

**Comment by chr0sy** [comment] 2021-01-04 20:52
[pmset_log.txt](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/5766729/pmset_log.txt)

Here you go. I also use the debug 1.2.0 version. it works fine (i just switched to airport, i was using itlwm heliport that was worse!), sometimes when i don't use the internet and computer is just standing, it might need to disconnect and reconnect to regain "momentum", anyways thats not an issue at all. my biggest issue now it's in the wake/sleep. can't get it to work, tried different bootargs such as darkwake, igfxonln=1 etc. and still nothing 🙁

**Comment by SkyrilHD** [comment] 2021-01-04 21:49
I see in the logs that it takes 2 minutes to wake the laptop up. Did you set your BIOS settings correctly and did you disable Power Nap and Wake on LAN? Also do you have a dGPU? Can you reproduce the issue with putting the laptop to sleep in other ways (for example: Clicking the sleep button in the apple menu, closing the lid). Can you recreate this behavior? 


https://user-images.githubusercontent.com/28839925/103582577-6b9ba200-4ede-11eb-8958-e09347d10631.mp4


I also uploaded OpenCore 0.6.5 which you can also test. Try without modifying the EFI, if it works fine try adding your modifications and find the culprit.

**Comment by chr0sy** [comment] 2021-01-04 22:12
I booted into safe mode with -x boot arg. 

Wake is maybe faster than a macbook!! Its like 1s even faster than your video! How do I diagnose from here? Any help? For sure it should be fixable.

**Comment by chr0sy** [comment] 2021-01-04 22:14
When screen goes black after inactivity in login screen from wake in safe mode,  if I close lid it goes to sleep and i can open lid and it wakes right up again. It seems like screen going black its a graphics issue i think

**Comment by SkyrilHD** [comment] 2021-01-04 22:17
That's weird. Could you run the command and send the file again?  And it might not be the EFI or macOS problem, but your apps how they deal with sleep.

**Comment by chr0sy** [comment] 2021-01-04 22:22
[pmset_log.txt](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/5767049/pmset_log.txt)

Here you go. Btw, I'm unable to mount Efi partition in safe boot using MountEFI. Any ideas how to mount it else?

**Comment by SkyrilHD** [comment] 2021-01-04 22:24
Sadly, you can't access the EFI partition in safe mode because a necessary kext is not loaded.

**Comment by chr0sy** [comment] 2021-01-04 22:25
> Sadly, you can't access the EFI partition in safe mode because a necessary kext is not loaded.

Yeah no worries I'm just gonna boot from my USB, my brain farted. See anything in the log?

**Comment by SkyrilHD** [comment] 2021-01-04 22:27
Found this... `Failure during wake: IGPU() : Some drivers failed to handle setPowerState`

**Comment by chr0sy** [comment] 2021-01-04 22:34
> Found this... `Failure during wake: IGPU() : Some drivers failed to handle setPowerState`

Any idea what it means / if it's resovable? It's weird because there are other hackintoshers with same laptop and same specs and do not have this problem

**Comment by SkyrilHD** [comment] 2021-01-04 22:38
I added -wegnoegpu as a boot-arg which disables the dGPU, maybe it does conflict with the iGPU. I need to do some research about that. Since our specs are same except the RAM, you could try my E7250 EFI which you can find [here](https://github.com/SkyrilHD/Dell-E7250-Hackintosh). Try that with an USB stick.

**Comment by chr0sy** [comment] 2021-01-04 22:41
> I added -wegnoegpu as a boot-arg which disables the dGPU, maybe it does conflict with the iGPU. I need to do some research about that. Since our specs are same except the RAM, you could try my E7250 EFI which you can find [here](https://github.com/SkyrilHD/Dell-E7250-Hackintosh). Try that with an USB stick.

Is the efi in the link you sent me now not the same as the efi in thread we are commenting on?

**Comment by SkyrilHD** [comment] 2021-01-04 22:43
It is the same except some ACPI patches and the boot-arg I just mentioned. Also I did just the E7250 EFI, so I know it definitely works.

**Comment by chr0sy** [comment] 2021-01-04 22:58
Tried your EFI from E7250, nothing. This is so frustrating :(.

**Comment by SkyrilHD** [comment] 2021-02-02 23:43
I've updated the EFI to OpenCore 0.6.6. You might want to check if it changes anything.

While I was on 0.6.5 I tried to break the EFI in every way. But sleep wasn't an issue at all...

**Comment by chr0sy** [comment] 2021-02-03 00:19
> I've updated the EFI to OpenCore 0.6.6. You might want to check if it changes anything.
> 
> While I was on 0.6.5 I tried to break the EFI in every way. But sleep wasn't an issue at all...

Do I just copy your entire folder or do I need to do something else?

**Comment by SkyrilHD** [comment] 2021-02-03 00:20
yep copying the entire folder is enough. I also suggest to try the EFI on an external USB drive, in case there are corrupted files.

**Comment by chr0sy** [comment] 2021-02-03 14:06
Tried it. Unfortunately doesn't work :(. It takes 4 minutes to wake up, and when it wakes up, all non-Mac apps like Chrome and such load into a black/dark grey screen.

**Comment by SkyrilHD** [comment] 2021-02-03 17:00
hmm same as before... now I actually doubt it is an EFI issue. Something is conflicting but I don't know what.

**Comment by chr0sy** [comment] 2021-02-03 17:22
How can I diagnose it?

**Comment by chr0sy** [comment] 2021-02-03 17:23
https://osxlatitude.com/forums/topic/14657-e7450-sleep-and-caps-lock-problem/

I also posted the issue here a while ago

**Comment by SkyrilHD** [comment] 2021-02-03 17:30
so that means you had this issue long time ago even before using my EFI. So, either try grabbing pmset logs again with `pmset -g log > pmset_log.txt` or try clearing NVRAM to clean out mess that comes with Clover. If it still doesn't work you might try installing macOS on a different partition or hard drive to make a clean install. If a clean install fixes your problem then the problem is your current installation

**Comment by chr0sy** [comment] 2021-02-08 15:04
Did a clean install, used your EFI folder. Still the same problem. This is weird

**Comment by chr0sy** [comment] 2021-02-08 15:48
Wake from sleep takes ±2 minutes now instead of 4. Also, another thing I noticed is that multi-gestures now work, but they don't work when I replace the command key with the control key. I do this so the command key becomes the Ctrl in my keyboard.

**Comment by SkyrilHD** [comment] 2021-02-08 22:54
Sad that it didn't fix the issue. Could you run the pmset log command again? You could try clearing your NVRAM if you haven't already.

The multi-gestures is an interesting point. I will try that out.

**Comment by chr0sy** [comment] 2021-02-09 00:13
https://pastebin.com/rzQxYErR

Here you go. Check last log, I did a sleep/wake. Laptop after wake is barely usable, all apps which are not made from Apple don’t load, system is super crashy and slow aswell. The timeline goes like this:

I close lid, computer goes to sleep well
I open lid, computer wakes and theres a completely black turned off display
After 40 seconds, display turns on but stays black for 1 minute and a half +-. Then it opens to the login screen

**Comment by chr0sy** [comment] 2021-02-09 12:11
Tried it again, and saw this:

`2021-02-09 12:51:00 +0100 Notification        	Display is turned on                                                       	          
2021-02-09 12:51:00 +0100 Assertions          	Kernel Idle sleep preventers: IODisplayWrangler          
2021-02-09 12:51:00 +0100 Assertions          	PID 182(mDNSResponder) Created MaintenanceWake "mDNSResponder:maintenance" 00:00:00  id:0x0xd000095f9 [System: PrevIdle DeclUser BGTask SRPrevSleep kCPU kDisp]          
2021-02-09 12:51:00 +0100 Assertions          	PID 182(mDNSResponder) Released MaintenanceWake "mDNSResponder:maintenance" 00:00:00  id:0x0xd000095f9 [System: PrevIdle DeclUser BGTask kDisp]          
2021-02-09 12:52:36 +0100 Assertions          	PID 469(SubmitDiagInfo) TimedOut PreventUserIdleSystemSleep "com.apple.SubmitDiagInfo" 00:02:32  id:0x0x1000095ad [System: PrevIdle DeclUser BGTask kDisp]          
2021-02-09 12:53:00 +0100 Wake                	Wake from Normal Sleep [CDNVA] : due to LID0/HID Activity Using AC (Charge:100%)           
2021-02-09 12:53:00 +0100 HibernateStats      	hibmode=3 standbydelaylow=10800 standbydelayhigh=86400                     	          2         	
2021-02-09 12:53:00 +0100 WakeTime            	WakeTime: 120.488 sec                                                      	          
2021-02-09 12:53:00 +0100 Kernel Client Acks  	Delays to Sleep notifications: [AppleHDADriver driver is slow(msg: SetState to 0)(507 ms)] [ApplePS2Controller driver is slow(msg: SetState to 0)(425 ms)] [en0 driver is slow(msg: WillChangeState to 0)(5278 ms)] 
2021-02-09 12:53:00 +0100 Kernel Client Acks  	Delays to Wake notifications: [AppleHDADriver driver is slow(msg: SetState to 1)(975 ms)] [PRT0 driver is slow(msg: SetState to 2)(1115 ms)] [ApplePS2Controller driver is slow(msg: SetState to 2)(1272 ms)] [AppleIntelFramebuffer driver is slow(msg: SetState to 2)(40379 ms)] [AppleIntelFramebuffer driver is slow(msg: SetState to 2)(40008 ms)] [AppleIntelFramebuffer driver is slow(msg: SetState to 2)(40022 ms)] `

Check the last two logs, from what it seems: 'AppleIntelFramebuffer'  is causing the majority of delay. There are three 40,000ms delays which amount to 2 minutes, the time it takes the computer to wake up. Could this be the issue?

**Comment by SkyrilHD** [comment] 2021-02-09 17:38
Let us see if it is the Framebuffer: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-hd-graphics-5300-6300-broadwell-processors

Here you can find different framebuffers for Broadwell processors. Try changing them with a Plist editor. For example: Xcode, ProperTree or PlistEdit Pro. Before you do any changes, be aware to have a backup EFI to boot from because changing the frame buffer could result to a black screen! Changing the framebuffer is very simple: Open the config, go to DeviceProperties>PciRoot(0x0)/Pci(0x2,0x0) and change the AAPL,ig-platform-id which you will find in the list.

I had 02001616 for my E7250 without issues but others had problems with HDMI, so yeah.

**Comment by chr0sy** [comment] 2021-02-09 22:44
None of them under "mobile" worked 🙁. This is such a bummer - I really thought I hit a breakthrough. The whole system works and everything is perfect except for this, and it really ruins it all because I always have to shutdown and wait for the laptop to turn back on !! 

Is there any other "road" we haven't explored yet that might result in this wake issue?

**Comment by SkyrilHD** [comment] 2021-02-10 08:14
Can you spam your keys like space-bar when you open the lid?

**Comment by chr0sy** [comment] 2021-02-10 08:17
You mean like press all the keys or just the space bar constantly after
opening the lid?

**Comment by SkyrilHD** [comment] 2021-02-10 08:21
Try both

**Comment by chr0sy** [comment] 2021-02-10 08:50
No, unfortunately it makes no difference

**Comment by SkyrilHD** [comment] 2021-02-10 09:45
I would try disabling kexts like Ethernet, audio etc.

You can do this by opening the config.plist and go to Kernel>Add. Necessary kexts are Lilu, VirtualSMC and WhateverGreen. Don't disable them.

For example you could disable IntelMausi and AppleALC which are for Ethernet and audio.

**Comment by chr0sy** [comment] 2021-02-10 11:48
I tried disabling all kexts except those 3, but laptop won’t even sleep
now. Also did I mention that in safe mode with -x bootarg the sleep wake
works perfectly?

**Comment by SkyrilHD** [comment] 2021-05-05 12:54
released another EFI update... any updates on this?

**Closed** 2021-05-20 11:55 UTC
Labels: question
